[package]
name = "mongoproxy"
version = "0.1.6"
authors = ["mpihlak <martin.pihlak@starship.co>"]
edition = "2018"

[dependencies]
byteorder = '1.3'
bson = '0.13'
log = '0.4'
env_logger = '0.6'
num-traits = '0.2'
num-derive = '0.2'
mio = '0.6'
hyper = '0.12'
prometheus = '0.7'
lazy_static = '1.4'
clap = '2.33'
