version: "3"
services:
  mongoproxy:
    container_name: mongoproxy
    image: mongoproxy:latest
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    command: ./mongoproxy --hostport mongodb-global.sandbox.int.starship.xyz:27017
    ports:
      - "9898:9898"
      - "27111:27111"
      - "27112:27112"
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - "27017:27017"
