version: "3"
services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy-dev
    ports:
      - "8001:8001"
      - "27018:27018"
    volumes:
      - ./log:/var/log
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
