version: "3"
services:
  envoy:
    container_name: envoy
    image: istio/proxyv2:1.5.0
    entrypoint:
      - /usr/local/bin/envoy
      - -c
      - /etc/envoy.yaml
      - -l
      - info
      - --service-cluster
      - proxy
    ports:
      - "8001:8001"
      - "27111:27111"
    volumes:
      - ${PWD}/envoy.yaml:/etc/envoy.yaml
      - ${PWD}/../target/wasm32-unknown-unknown/release/envoy_wasm.wasm:/usr/local/lib/mongoproxy.wasm
  mongoproxy:
    container_name: mongoproxy
    image: mpihlak/mongoproxy:v0.5.3
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
    command: ./mongoproxy --proxy 27112:mongodb:27017
    ports:
      - "9898:9898"
      - "27112:27112"
  mongodb:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - "27017:27017"
